### ISSUE TITLE
Compilation errors in build

### ISSUE THREAD

**Issue by remojansen** [inversify/InversifyJS#45]
There is an error in the build logs:

https://travis-ci.org/inversify/InversifyJS/builds/103853460

```
[14:19:34] Starting 'build-test'...
test/inject_annotation.test.ts(1,1): error TS6053: File '/home/travis/build/inversify/InversifyJS/typings/tsd.d.ts' not found.
test/inject_annotation.test.ts(3,24): error TS2307: Cannot find module 'chai'.
test/inject_annotation.test.ts(6,1): error TS2304: Cannot find name 'describe'.
test/inject_annotation.test.ts(7,4): error TS2304: Cannot find name 'it'.
test/inject_annotation.test.ts(19,4): error TS2304: Cannot find name 'it'.
test/inject_annotation.test.ts(32,4): error TS2304: Cannot find name 'it'.
test/inject_annotation.test.ts(45,4): error TS2304: Cannot find name 'it'.
test/inject_annotation.test.ts(58,4): error TS2304: Cannot find name 'it'.
test/kernel.test.ts(1,1): error TS6053: File '/home/travis/build/inversify/InversifyJS/typings/tsd.d.ts' not found.
test/kernel.test.ts(3,24): error TS2307: Cannot find module 'chai'.
test/kernel.test.ts(9,1): error TS2304: Cannot find name 'describe'.
test/kernel.test.ts(11,3): error TS2304: Cannot find name 'it'.
test/kernel.test.ts(23,3): error TS2304: Cannot find name 'it'.
test/kernel.test.ts(51,3): error TS2304: Cannot find name 'it'.
test/kernel.test.ts(66,3): error TS2304: Cannot find name 'it'.
test/kernel.test.ts(87,3): error TS2304: Cannot find name 'it'.
test/kernel.test.ts(111,3): error TS2304: Cannot find name 'it'.
test/kernel.test.ts(131,3): error TS2304: Cannot find name 'it'.
test/kernel.test.ts(143,3): error TS2304: Cannot find name 'it'.
test/kernel.test.ts(177,3): error TS2304: Cannot find name 'it'.
test/kernel.test.ts(213,3): error TS2304: Cannot find name 'it'.
test/kernel.test.ts(249,3): error TS2304: Cannot find name 'it'.
test/lookup.test.ts(1,1): error TS6053: File '/home/travis/build/inversify/InversifyJS/typings/tsd.d.ts' not found.
test/lookup.test.ts(3,24): error TS2307: Cannot find module 'chai'.
test/lookup.test.ts(6,1): error TS2304: Cannot find name 'describe'.
test/lookup.test.ts(8,3): error TS2304: Cannot find name 'it'.
test/lookup.test.ts(15,3): error TS2304: Cannot find name 'it'.
test/lookup.test.ts(20,3): error TS2304: Cannot find name 'it'.
test/lookup.test.ts(25,3): error TS2304: Cannot find name 'it'.
test/lookup.test.ts(34,3): error TS2304: Cannot find name 'it'.
test/type_binding.test.ts(1,1): error TS6053: File '/home/travis/build/inversify/InversifyJS/typings/tsd.d.ts' not found.
test/type_binding.test.ts(3,24): error TS2307: Cannot find module 'chai'.
test/type_binding.test.ts(7,1): error TS2304: Cannot find name 'describe'.
test/type_binding.test.ts(9,3): error TS2304: Cannot find name 'it'.
test/type_binding.test.ts(30,3): error TS2304: Cannot find name 'it'.
test/type_binding.test.ts(38,3): error TS2304: Cannot find name 'it'.
[14:19:34] TypeScript: 36 semantic errors
[14:19:34] TypeScript: emit succeeded (with errors)
```

I think this issues was introduced by https://github.com/inversify/InversifyJS/pull/39

It looks like is missing the `tsd.d.ts` file: 

```
'/home/travis/build/inversify/InversifyJS/typings/tsd.d.ts' not found.
```

We need to fix it but even more important is to **ensure that the Travis CI build fails if there are compilation errors**.

**Comment by remojansen** [comment]
@Jameskmonger do you mind if I assign this issue to you?

**Comment by Jameskmonger** [comment]
That's fine @remojansen, assign me and I will take a look!

**Comment by remojansen** [comment]
Thanks :rainbow: :+1:
