### ISSUE TITLE
error TS2656: Exported external package?

### ISSUE THREAD

**Issue by kareemaly** [inversify/InversifyJS#36]
I get this error when I compile with typescript v1.7.3

```
error TS2656: Exported external package typings file '<path>/node_modules/inversify/type_definitions/inversify.d.ts' is not a module. Please contact the package author to update the package definition.
```

I made it work by manualy removing `"typings": "type_definitions/inversify.d.ts"` from inversify package.json and importing inversify.d.ts file in my tsd.d.ts file

**Comment by tenowg** [comment]
This issue was attempted at #32 but seems that the format for using `typings` is different then that required by /// references and will require either a new d.ts file and thus an additional file to maintain or someone to figure it out.

**Comment by remojansen** [comment]
I'm going to close this issue to ensure that we only have one unique issue to refer to this problem. You can follow the updates at #46
